### ISSUE TITLE
As long as I import a node module it fails to work

### ISSUE THREAD

**Issue by qiulang** [vitalets/mocha-es6-modules#4]
First of all, [your article](https://medium.com/dailyjs/running-mocha-tests-as-native-es6-modules-in-a-browser-882373f2ecb0) and example is very helpful. Thank you!

But as long as I import a node module, as any "real" project will do, it fails to work. For example I add 

`import debug from 'debug'` to `sum.js` then I will get the error

`Uncaught TypeError: Failed to resolve module specifier "debug". Relative references must start with either "/", "./", or "../".`

Any idea how can I fix it ? The last resort of course will be using webpack to bundle them into a single file, but I was hoping if there is any easy solution without bundling.

**Comment by vitalets** [comment]
As web browser does not know anything about node module structure you should import it by full path, e.g.
```js
import debug from './node_modules/debug/src/browser.js';
```
In the future [package maps](https://github.com/domenic/package-name-maps) should help with it.

**Comment by Seanmclem** [comment]
I have the same issue. using the full path doesn't fix the issue. I just get a 404 for the file now

**Comment by skinet92** [comment]
solutions...???!!

**Comment by 121Unicorns** [comment]
I have the same issue. Trying to import node-rsa

**Comment by 71iq** [comment]
I have the saem issue. Anyone solved it yet?
